# **Pandas**
## **Python Data Analysis** - core Python lib that provides high-performance, easy-to-use data structures and data analysis tools.

Skills Test 1 (Python) - The week after next week (Sept. 17)

In [75]:
import pandas as pd

Data Series - is a 1-D labeled array capable of holding any data type

In [76]:
s = pd.Series([3, -5, 7, 4], index=['a','b','c','d'])
s

a    3
b   -5
c    7
d    4
dtype: int64

Data Frames - 2D labeled data structure with col. of different data types

In [77]:
#Step 1: Create a Dictionary
data = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
        'Population': [11190846,1303171035, 207847528]}
#Step 2: Create a Dataframe
df = pd.DataFrame(data, columns=['Country','Capital','Population'])
df

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

## **Python Demo 1:** Creating a data series and data frames using Pandas

In [78]:
Global_PS4_sales = pd.Series([10.0,30.2,35.9,73.6,91.6,94.7],
                    index=[2014,2015,2016,2017,2018,2019])
Global_PS4_sales

2014    10.0
2015    30.2
2016    35.9
2017    73.6
2018    91.6
2019    94.7
dtype: float64

In [79]:
data = {'Character': ['Killua', 'Kurapika', 'Gon', 'Chrollo', 'Hisoka'],
        'Nen': ['Kanmuru', 'Jail Chain', 'Jajanken', 'Bandit Secret', 'Bungee Gum'],
        'Nen Type': ['Transmuter', 'Conjurer', 'Enhancer', 'Specialist', 'Transmuter'],
        'Votes': [7488, 7000, 2472, 1904, 1144]}
HxH_Popularity_Poll = pd.DataFrame(data, columns=['Character', 'Nen', 'Nen Type', 'Votes'])
HxH_Popularity_Poll

  Character            Nen    Nen Type  Votes
0    Killua        Kanmuru  Transmuter   7488
1  Kurapika     Jail Chain    Conjurer   7000
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904
4    Hisoka     Bungee Gum  Transmuter   1144

In [80]:
HxH_Popularity_Poll.to_csv('MyDataframe.csv')

In [81]:
aqd = pd.read_csv('aqd.csv')
aqd

     Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0             1   41.0    190.0   7.4    67      5    1
1             2   36.0    118.0   8.0    72      5    2
2             3   12.0    149.0  12.6    74      5    3
3             4   18.0    313.0  11.5    62      5    4
4             5    NaN      NaN  14.3    56      5    5
..          ...    ...      ...   ...   ...    ...  ...
148         149   30.0    193.0   6.9    70      9   26
149         150    NaN    145.0  13.2    77      9   27
150         151   14.0    191.0  14.3    75      9   28
151         152   18.0    131.0   8.0    76      9   29
152         153   20.0    223.0  11.5    68      9   30

[153 rows x 7 columns]

In [82]:
aqd.head() #gets the first 5 rows

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    NaN      NaN  14.3    56      5    5

In [83]:
aqd.tail() #gets the last 5 rows

     Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
148         149   30.0    193.0   6.9    70      9   26
149         150    NaN    145.0  13.2    77      9   27
150         151   14.0    191.0  14.3    75      9   28
151         152   18.0    131.0   8.0    76      9   29
152         153   20.0    223.0  11.5    68      9   30

---

## **Python Demo 2:** Subsetting, slicing, and indexing of data structures

### **subsetting** -> certain element (1)

In [84]:
s = Global_PS4_sales
s

2014    10.0
2015    30.2
2016    35.9
2017    73.6
2018    91.6
2019    94.7
dtype: float64

In [85]:
df = HxH_Popularity_Poll
df

  Character            Nen    Nen Type  Votes
0    Killua        Kanmuru  Transmuter   7488
1  Kurapika     Jail Chain    Conjurer   7000
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904
4    Hisoka     Bungee Gum  Transmuter   1144

In [86]:
s[2016]

35.9

In [87]:
#iloc - m row, n col in indexes (i - generic index)
df.iloc[[3],[2]]

     Nen Type
3  Specialist

In [88]:
#loc - m row, column name 
df.loc[[2],['Nen']]

        Nen
2  Jajanken

### **Slicing** -> getting a portion

---

In [89]:
s #with 0 = 2014

2014    10.0
2015    30.2
2016    35.9
2017    73.6
2018    91.6
2019    94.7
dtype: float64

In [90]:
s[1:4] #range of the data you want to extract; [1 (inclusive), 4 (exclusive)]

2015    30.2
2016    35.9
2017    73.6
dtype: float64

In [91]:
df

  Character            Nen    Nen Type  Votes
0    Killua        Kanmuru  Transmuter   7488
1  Kurapika     Jail Chain    Conjurer   7000
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904
4    Hisoka     Bungee Gum  Transmuter   1144

In [92]:
df[1:4]

  Character            Nen    Nen Type  Votes
1  Kurapika     Jail Chain    Conjurer   7000
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904

In [93]:
df.loc[:, ['Nen Type']] #empty spaces before and after ":" means it will take the whole given table

     Nen Type
0  Transmuter
1    Conjurer
2    Enhancer
3  Specialist
4  Transmuter

In [94]:
df.loc[0:3, ['Nen Type']] #second index is inclusive because it pertains to the exact position/location of the element

     Nen Type
0  Transmuter
1    Conjurer
2    Enhancer
3  Specialist

In [95]:
df.loc[[0,2],['Character', 'Votes']] 
# [index_1, index_2] means you will exclusively isolate this part of the table; it is particular about the order YOU give

  Character  Votes
0    Killua   7488
2       Gon   2472

In [96]:
df.loc[[4,0,2,1],['Character', 'Votes']]

  Character  Votes
4    Hisoka   1144
0    Killua   7488
2       Gon   2472
1  Kurapika   7000

### **Indexing** -> with given conditions
- getting a certain element but with given conditions (boolean operators)
---

In [97]:
s

2014    10.0
2015    30.2
2016    35.9
2017    73.6
2018    91.6
2019    94.7
dtype: float64

In [98]:
s[s>60]

2017    73.6
2018    91.6
2019    94.7
dtype: float64

In [99]:
df

  Character            Nen    Nen Type  Votes
0    Killua        Kanmuru  Transmuter   7488
1  Kurapika     Jail Chain    Conjurer   7000
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904
4    Hisoka     Bungee Gum  Transmuter   1144

In [100]:
df.loc[(df['Votes']>1000)&(df['Votes']<5000)] # locating elements from dictionary

  Character            Nen    Nen Type  Votes
2       Gon       Jajanken    Enhancer   2472
3   Chrollo  Bandit Secret  Specialist   1904
4    Hisoka     Bungee Gum  Transmuter   1144

In [101]:
df.loc[df['Nen Type']=='Transmuter'] # == equivalence

  Character         Nen    Nen Type  Votes
0    Killua     Kanmuru  Transmuter   7488
4    Hisoka  Bungee Gum  Transmuter   1144

In [102]:
df.loc[(df['Nen']=='Kanmuru'), ['Character']] #asks for who is the character under Nen with Kanmuru

  Character
0    Killua

In [106]:
df.loc[(df['Nen']=='Kanmuru')]

  Character      Nen    Nen Type  Votes
0    Killua  Kanmuru  Transmuter   7488

In [103]:
df.loc[df['Nen Type']=='Transmuter',['Character','Nen','Votes']]

  Character         Nen  Votes
0    Killua     Kanmuru   7488
4    Hisoka  Bungee Gum   1144